template:
  name: go
  env:
    LD_RELEASE_GO_IMPORT_PATH: github.com/launchdarkly/go-ntlmssp

publications:
  - url: https://godoc.org/github.com/launchdarkly/go-ntlmssp
    description: documentation
